### PR TITLE
Nx 20 support

### PR DESCRIPTION
**Pull request by pawel-twardziak**
- migrate workspace to NX 20
- align the generators code to the NX API: library and application
- clean up the generators code: library and application (much useless code)

### CODE REVIEW

**Comment by NathanWalker** [comment]
Thank you for kicking this off!

**Comment by pawel-twardziak** [comment]
hi @NathanWalker I need this migration for my green field project. Almost done, tested and all work. Still some chores to get done.

**Comment by pawel-twardziak** [comment]
I will be working on this for the next week - so should be done soon :)

**Comment by NathanWalker** [comment]
ok excellent @pawel-twardziak just ping when ready and we'll merge this into the other pending PR which is ton of executor standardization improvements before releasing v20.

**Comment by pawel-twardziak** [comment]
Hi @NathanWalker I see there has beed done a huge job out there https://github.com/NativeScript/nx/pull/57
Do you want to merge my work into that one?

**Comment by NathanWalker** [comment]
If you want to try the merge, you could try merging his into yours or vice versa - ideally we want to merge both your work here and that one.

**Comment by pawel-twardziak** [comment]
I don't like merging other people's work with anything but the main :) Simply out of respect for someone else's work.
I recommend merging one of the work first - mine is simpler (just one responsibility) so this could be the first imho.
That https://github.com/NativeScript/nx/pull/57 PR takes many resposibilities which is not the best approach 😆  so we could continue on that one next to eventually get both of them done :)

**Comment by pawel-twardziak** [comment]
And I am activly migrating https://github.com/nxext/nx-extensions (it is done, now fixing period) to NX20 too, so I work on two fronts 😆

**Comment by NathanWalker** [comment]
Agreed, just make this ready for review when ready and we'll merge this first then.

**Comment by pawel-twardziak** [comment]
Thank you @NathanWalker 👍 I am sluggish as being sick but I am speeding up! 😺
I assume I should get mine done by Saturday (including).

**Comment by pawel-twardziak** [comment]
Hi @NathanWalker I will be continuing on it this Sunday (unfortunately tomorrow I cannot). Expect my PR ready by 4pm. I was delayed due to illness.

**Comment by pawel-twardziak** [comment]
@NathanWalker ready to CR. In general, for some reason, fixing package dep version while `lint --fix` does not work. I dunno why. Need to investigate it a bit more. For now, I did it manually.

**Comment by pawel-twardziak** [comment]
@NathanWalker are you there? :)

**Comment by NathanWalker** [comment]
We’ll check that out and get this merged today

**Review by NathanWalker — APPROVED** [review]

**Pull request merged**
